services:
  akabot:
    env_file: .env
    build: .
    develop:
      watch:
        - path: features/
          target: /app/features
          action: sync+restart
        - path: utils/
          target: /app/utils
          action: sync+restart
        - path: main.py
          target: /app
          action: sync+restart
        - path: database.py
          target: /app
          action: sync+restart
        - path: lang/
          target: /app/lang
          action: sync
        - path: Dockerfile
          action: rebuild
        - path: requirements.txt
          action: rebuild
    networks:
      - akabot
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mldchan
      MONGO_INITDB_ROOT_PASSWORD: changeme
    networks:
      - akabot
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mldchan
      ME_CONFIG_MONGODB_ADMINPASSWORD: changeme
      ME_CONFIG_MONGODB_URL: mongodb://mldchan:changeme@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - akabot

networks:
  akabot:
    driver: bridge
